---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - build.contrib.flux.io
  resources:
  - dockerbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.contrib.flux.io
  resources:
  - dockerbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - build.contrib.flux.io
  resources:
  - dockerbuilds/status
  verbs:
  - get
  - patch
  - update
